import { db } from "@/lib/db";
import { ProductServicesProps } from "@/types/products";

import { Prisma } from "@prisma/client";
import { unstable_cache } from "next/cache";

export interface ProductQueryParams {
  page?: string;
  catId?: string;
  search?: string;
  min?: string;
  max?: string;
  sort?: "asc" | "desc";
}

// GET Filtered Products (Cached for Public)
export async function getFilteredProducts(params: ProductQueryParams) {
  // 🎯 THE WRAPPER: define the cached logic
  const getCachedData = unstable_cache(
    async (p: ProductQueryParams) => {
      const pageSize = 10;
      const { page = "1", catId, search, min, max, sort } = p;

      const where: Prisma.ProductWhereInput = {};
      if (catId) where.categoryId = catId;

      if (search) {
        where.OR = [
          { title: { contains: search, mode: "insensitive" } },
          { description: { contains: search, mode: "insensitive" } },
        ];
      }

      if (min || max) {
        where.salePrice = {
          gte: min ? parseFloat(min) : undefined,
          lte: max ? parseFloat(max) : undefined,
        };
      }

      const orderBy: Prisma.ProductOrderByWithRelationInput =
        sort === "asc" || sort === "desc"
          ? { salePrice: sort }
          : { createdAt: "desc" };

      return await db.product.findMany({
        where,
        orderBy,
        skip: (parseInt(page) - 1) * pageSize,
        take: pageSize,
        include: { category: true },
      });
    },
    [`products-list-${JSON.stringify(params)}`], // 🎯 Cache Key
    {
      tags: ["products-list"], // 🎯 Tag for revalidation
      revalidate: 600,
    },
  );

  // 🎯 THE INVOCATION: Call the cached function with the params
  return await getCachedData(params);
}

// GET Single Product
export async function getProductById(id: string) {
  return await db.product.findUnique({
    where: { id },
    include: { store: true, category: true },
  });
}

// CREATE Bulk Products (Multi-Store)
export async function createStoreProducts(data: ProductServicesProps) {
  const {
    productImages,
    storeIds,
    storeId,
    categoryId,
    imageUrl,
    userId,
    slug,
    ...rest
  } = data;

  const operations = storeIds.map((storeId: string, id: React.Key) =>
    db.product.create({
      data: {
        ...rest,
        slug: `${slug}+${id}`,
        imageUrl:
          productImages && productImages.length > 0 ? productImages[0] : "",
        // Parse numbers from your POST request
        qty: Number(data.qty),
        productPrice: Number(data.productPrice),
        salePrice: Number(data.salePrice),
        wholesaleQuantity: Number(data.wholesaleQuantity),
        wholesalePrice: Number(data.wholesalePrice),
        // Relations
        category: { connect: { id: data.categoryId } },
        user: { connect: { id: userId } },
        store: { connect: { id: storeId } },
      },
    }),
  );

  return await db.$transaction(operations);
}

export async function getProductBySlug(slug: string) {
  return unstable_cache(
    async () => {
      return await db.product.findUnique({
        where: {
          // Use the new composite key name generated by Prisma
          slug: slug,
        },
        include: { store: true, category: true },
      });
    },
    [`product-slug-${slug}`],
    { tags: [`product-${slug}`] },
  )();
}

export async function updateProduct(
  productId: string,
  data: ProductServicesProps,
) {
  // 1. 🛡️ Fetch the product to verify existence and get context
  const originalProduct = await db.product.findUnique({
    where: { id: productId },
  });

  if (!originalProduct) {
    throw new Error("Product not found.");
  }

  // Unique Name Check (Simplified)
  // Check if the NEW name is taken by a DIFFERENT product in THIS store
  const existingConflict = await db.product.findFirst({
    where: {
      slug: data.slug,
      storeId: originalProduct.storeId, // Only check the current store
      NOT: { id: productId }, // Exclude current record
    },
  });

  if (existingConflict) {
    throw new Error(`The name "${data.title}" is already taken in this store.`);
  }

  const mainImage = data.productImages?.[0] || "";

  const { categoryId, storeId, userId, store, ...rest } = data;

  // 3. 🎯 Direct Update
  // We no longer loop or deleteMany. We just update the record you are looking at.
  try {
    return await db.product.update({
      where: { id: productId },
      data: {
        ...rest,
        title: data.title,
        slug: data.slug,
        qty: Number(data.qty),
        productPrice: Number(data.productPrice),
        salePrice: Number(data.salePrice),
        description: data.description,
        imageUrl: mainImage,
        productImages: data.productImages,
        wholesaleQuantity: Number(data.wholesaleQuantity),
        wholesalePrice: Number(data.wholesalePrice),
        category: { connect: { id: data.categoryId } },
        // We keep storeIds as a reference array if you need it,
        // but we don't use it to trigger syncs anymore.
        // storeIds: data.storeIds,
      },
    });
  } catch (error) {
    console.error("Update Error:", error);
    throw new Error("Failed to update product.");
  }
}

export async function getAllProducts() {
  return unstable_cache(
    async () => {
      return await db.product.findMany({
        orderBy: { createdAt: "desc" },
      });
    },
    ["all-products-list"],
    { tags: ["products-list"] },
  )();
}

export async function deleteProduct(productId: string) {
  try {
    return await db.product.delete({
      where: { id: productId },
    });
  } catch (error) {
    console.error("Delete Error:", error);
    throw new Error("Failed to delete the product from this store.");
  }
}
