import { Metadata } from "next";

import ErrorBoundary from "@/components/ErrorBoundary";
import { ThemeProvider } from "@/providers/ThemeProvider";
import "../styles/main.scss";

export const metadata: Metadata = {
  title: "Multi Vendor E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ErrorBoundary>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
